### ISSUE TITLE
Compress image before upload

### ISSUE THREAD

**Issue by gasparteixeira** [polycarpou/expo-camera-roll-select#11]
Hello, 

Thank you for the nice stuff! 

So I want to upload selected pictures. Could I compress it before I upload to server?

**Comment by polycarpou** [comment]
Hey!
Expo has a library called the ImageManipulator which might be what you are looking for. https://docs.expo.io/versions/latest/sdk/imagemanipulator/
Here you pass in the uri (which you can get from the camera roll selector) and resize/crop/compress options depending on what you like.
