### ISSUE TITLE
Videos not showing up 

### ISSUE THREAD

**Issue by AakashRainaClairvoyant** [polycarpou/expo-camera-roll-select#12]
I tried setting up the groupTypes:"All" in the params for getPhotos method along with mime types, but the videos are not showing up only images are. Any help will be appreciated.

**Comment by polycarpou** [comment]
Hey! 
To show videos you need to change the assetType param rather than groupType. 
More info here: https://facebook.github.io/react-native/docs/cameraroll#getphotos
You might also need to change some more things to actually show the different videos.
