### ISSUE TITLE
Option to extract Exif data from images?

### ISSUE THREAD

**Issue by btroia** [polycarpou/expo-camera-roll-select#7]
I don't believe this currently can be done without linking. Although Expo has added an `exif` option to their `ImagePicker` component. I think it will require them to add the same option to their `ImageManipulator` component in order to allow for Exif data extraction on _any_ image - please upvote my feature request on Canny! 👊 https://expo.canny.io/feature-requests/p/add-exif-data-option-in-expoimagemanipulator

**Comment by polycarpou** [comment]
👍upvoted!

**Comment by xlcrr** [comment]
+1

**Comment by borgogelli** [comment]
+1
