### ISSUE TITLE
Breaks upon upgrading to Expo 27

### ISSUE THREAD

**Issue by TySol** [polycarpou/expo-camera-roll-select#8]
I thought maybe this had to do with Permissions, but even after asking for both CameraRoll and Camera, it still just displays "Loading" on ImageBrowser screen 

I upgraded the master from v.23 to v.27 to verify, and it does indeed only break when going from 26 to 27

**Comment by TySol** [comment]
Seems the issue is getPhotos isn't being called initially on ImageBrowser screen for some reason now.  

A simple fix is - 

  componentDidMount() {
    this.getPhotos()
  }

Thanks for this awesome package Michael Polycarpou!

**Comment by polycarpou** [comment]
Hey! thanks for heads up. 
I upgraded to expo 27 and fixed the bug
